2章冒頭と2.1節を翻訳しました。
lean-ja/fp-lean-ja pull request #2
Opened 2023-10-21 05:26 UTC by ihuku

2章冒頭と2.1節を翻訳しました。
それほど大きな意訳は行なっていませんが、意味の変わらない範囲で言葉を補ったり語順を入れ替えている箇所もあります。
あと、"side effects"は「副作用」ですが、"effects"単体で出てきたときの和訳に悩みました…。とりあえず「作用」としています。

2023-10-21 10:46 UTC, ihuku commented
2.2節も翻訳しました。
“effects”は「副作用」で良い気がしてきたため、そのように訳しています。
違和感なさそうでしたら、2.1節も同じように見直そうと思いますので、お知らせください。

2023-10-21 12:20 UTC, Seasawher commented
「プログラマー」「ユーザー」「アクセサー」の最後の長音をこちらで除いておきます

2023-10-21 14:41 UTC, Seasawher commented
@ihuku また後日続きをレビューします．

2023-10-22 08:45 UTC, Seasawher requested changes
@ihuku 最後まで終わっていませんが，いったんお返しします．

理由について詳細に書くことができていない部分もありますが，おおむね下記に気を付けて修正をリクエストした箇所とその周辺を見直してください．

* 和訳が直訳調にならないようにしてください．特に have は「持つ」と訳すだけでなくて，「～がある」などと訳す方法もあります．文脈に応じて自然な方を選択してください．
* 日本語の助詞の扱いに気を付けてください．同じ主語を表すのにも「は」「が」「の」を使い分ける必要があります．
* 訳から単語が落ちていることがあります．特に DeepL は，単語や文章を抜かして訳を生成してしまいやすいので気を付けてください．

---

すみませんが分量が多くてレビュー作業が追い付かないので，いったん 2 Hello world と 2.1 Running a Program の翻訳をマージすることを目標にさせてください．2.2 節の翻訳はこのブランチからはリバートして，このブランチのマージが終わってから出し直してくださるようお願いします．

2023-10-22 08:45 UTC, Seasawher commented on functional-programming-lean/src/hello-world/running-a-program.md
> +これらの行は，ライブラリアクション`IO.getStdin`および`IO.getStdout`を実行して`stdin`と`stdout`のハンドルを取得します．`do`ブロックでは，通常の式とは異なり，`let`にはやや異なる意味があります．通常，`let`で導入されたローカル定義は，すぐにそのローカル定義に続く式でしか使用できません．`do`ブロックでは，`let`によって導入されたローカル束
> `do`ブロックでは，通常の式とは異なり，`let`にはやや異なる意味があります．

* 助詞の「は」の使い方がおかしいです．
* 何と何が異なると言っているのかわかりにくい文章になっています．

---

`do` ブロックの中の `let` は，通常の式の中の `let` とはやや異なる意味を持ちます．

2023-10-22 08:45 UTC, Seasawher commented on functional-programming-lean/src/hello-world/running-a-program.md
> +これらの行は，ライブラリアクション`IO.getStdin`および`IO.getStdout`を実行して`stdin`と`stdout`のハンドルを取得します．`do`ブロックでは，通常の式とは異なり，`let`にはやや異なる意味があります．通常，`let`で導入されたローカル定義は，すぐにそのローカル定義に続く式でしか使用できません．`do`ブロックでは，`let`によって導入されたローカル束
> Additionally, `let` typically connects the name being defined to its definition using `:=`, while some `let` bindings in `do` use a left arrow (`←` or `<-`) instead.
> さらに，通常，`let`は名前を定義の右側に`:=`を使用しますが，`do`の一部の`let`束縛では，代わりに左矢印(`←`または`<-`)を使用します．

---

さらに，通常 `let` は `:=` を使って定義される名前とその定義を結びつけますが，`do` 内部の `let` 束縛においては，代わりに左矢印（`←`または `<-`）を使うことがあります．

2023-10-22 08:45 UTC, Seasawher commented on functional-programming-lean/src/hello-world/running-a-program.md
> +これらの行は，ライブラリアクション`IO.getStdin`および`IO.getStdout`を実行して`stdin`と`stdout`のハンドルを取得します．`do`ブロックでは，通常の式とは異なり，`let`にはやや異なる意味があります．通常，`let`で導入されたローカル定義は，すぐにそのローカル定義に続く式でしか使用できません．`do`ブロックでは，`let`によって導入されたローカル束
> Using an arrow means that the value of the expression is an `IO` action that should be executed, with the result of the action saved in the local variable.
> 矢印を使用すると，式の右側の値が実行されるべき`IO`アクションで，そのアクションの結果がローカル変数に保存されます．

---

矢印を使用するということは，式の値が IO アクションであり，そのアクションの実行結果をローカル変数に保存するということを意味します．

2023-10-22 08:45 UTC, Seasawher commented on functional-programming-lean/src/hello-world/running-a-program.md
> +これらの行は，ライブラリアクション`IO.getStdin`および`IO.getStdout`を実行して`stdin`と`stdout`のハンドルを取得します．`do`ブロックでは，通常の式とは異なり，`let`にはやや異なる意味があります．通常，`let`で導入されたローカル定義は，すぐにそのローカル定義に続く式でしか使用できません．`do`ブロックでは，`let`によって導入されたローカル束
> `IO.getStdin` and `IO.getStdout` are `IO` actions in order to allow `stdin` and `stdout` to be locally overridden in a program, which can be convenient.
> `IO.getStdin`および`IO.getStdout`は`stdin`と`stdout`をプログラム内でローカルに上書きできるようにするために`IO`アクションです．これは便利なことです．

---

`IO.getStdin` および `IO.getStdout` は `stdin` と `stdout` をプログラム内でローカルに上書きできるようにするための便利な IOアクションです．

2023-10-22 08:45 UTC, Seasawher commented on functional-programming-lean/src/hello-world/running-a-program.md
> +これらの行は，ライブラリアクション`IO.getStdin`および`IO.getStdout`を実行して`stdin`と`stdout`のハンドルを取得します．`do`ブロックでは，通常の式とは異なり，`let`にはやや異なる意味があります．通常，`let`で導入されたローカル定義は，すぐにそのローカル定義に続く式でしか使用できません．`do`ブロックでは，`let`によって導入されたローカル束
> Cのようにグローバル変数であった場合，これらを上書きする有意義な方法はありませんが，`IO`アクションは実行されるたびに異なる値を返すことができます．

* ここでは指示語を残さない方が良いです
* meaningful の意味がとりづらいのですが，おそらく↓のようなことではないかと思います．

---

C 言語のように `stdin` と `stdout` がグローバル変数であったら，（Lean では一度束縛した値は変更できないので）これを上書きすることはできませんが，IO アクションなら実行ごとに異なる値を返してもおかしくありません．

2023-10-22 08:45 UTC, Seasawher commented on functional-programming-lean/src/hello-world/running-a-program.md
> +最初の行は質問を`stdout`に書き込み，2番目の行は`stdin`から入力をリクエストし，3番目の行は入力行から末尾の改行（および他の末尾の空白）を削除します．`name`の定義では，`String.dropRightWhile`は`IO`アクションではなく，通常の文字列関数であるため，`:=`ではなく`←`を使用しています．
> `String.dropRightWhile`は`IO`アクションではなく，通常の文字列関数であるため，`:=`ではなく`←`を使用しています．

本文のコード例と内容が合致していません．訳文だけでなくコード例も確認して言っている内容が合っているか確認してください．

---

`String.dropRightWhile` は IO アクションではなく，通常の文字列関数であるため，`←` ではなく`:=` を使用しています．

2023-10-22 22:15 UTC, ihuku commented
@Seasawher レビューありがとうございました。表記ルールに則っていない箇所については失礼しましたm(_ _)m
コメント頂いた部分は順次見直します。

> すみませんが分量が多くてレビュー作業が追い付かないので，いったん 2 Hello world と 2.1 Running a Program の翻訳をマージすることを目標にさせてください．2.2 節の翻訳はこのブランチからはリバートして，このブランチのマージが終わってから出し直してくださるようお願いします．

了解です。2.2節step-by-step.md関連のcommitは、いったんrevertします。

2023-10-23 15:32 UTC, ihuku commented on functional-programming-lean/src/hello-world.md
> +[前の章](./getting-to-know.md)では，Leanにおける関数型プログラミングの基本を紹介しましたが，この章ではプロジェクトを作成し，コンパイルして，その結果を実行する一連の方法を説明します．なお，周囲の環境と対話するプログラム（例えば，標準入力からの入力を読み取ったりファイルを作成したりすること）は，計算を「数学的な式の評価」と解釈することとの調和が難しいものです．そのためこ
提案いただいた文章をベースに表現を見直しました。最後の一文のみ、提案いただいたものから語順の入れ替え等をさせていただきました。

コミットIDは[0a067b4d1f4a10951ec465273a6b97d1d73bc154](https://github.com/lean-ja/fp-lean-ja/pull/2/commits/0a067b4d1f4a10951ec465273a6b97d1d73bc154)です。

2023-11-01 10:38 UTC, Seasawher commented
@ihuku ご無沙汰しております．その後いかがでしょうか？

もしもお忙しいようでしたら，こちらでコミットをなんとか取り込んでマージまで持っていけないかやってみようと思っております．

2023-11-01 14:55 UTC, ihuku commented
@Seasawher お気遣いありがとうございます。しばらく間が空いてしまい失礼しました。

状況ですが、2.2節のstep-by-stepは一旦revertしたのと、2 Hello worldは頂いたコメントを踏まえて修正しました。
これらについてはcommit済みですので、ご確認いただけますと幸いです。（GitHubに不慣れでして…。私は提出したつもりなものの、もし、Seasawherさん側で確認できないようなステータスでしたら申し訳ありません）

2.1 Running a Programについては手を付けられていないのが現状ですので、Seasawherさんの方で取り込んでいただけるのであればお願いしても宜しいでしょうか。

ちなみに、もし、私の初版を直すより一から訳した方が早い…、という感触でしたら、2.1もrevertしても構いません。この点については遠慮なくお知らせください。

2023-11-03 07:18 UTC, Seasawher commented
@ihuku 返信ありがとうございます．

> （GitHubに不慣れでして…。私は提出したつもりなものの、もし、Seasawherさん側で確認できないようなステータスでしたら申し訳ありません）

確認できております．大丈夫ですよ．

> 2.1 Running a Programについては手を付けられていないのが現状ですので、Seasawherさんの方で取り込んでいただけるのであればお願いしても宜しいでしょうか。

今すぐは難しいですが，手が空いた時にマージしてこちらで修正しようかと思っております．

2023-11-04 11:44 UTC, merged

2023-11-04 11:46 UTC, Seasawher commented
@ihuku お疲れ様です．こちらで見直しを行い，マージいたしました．

修正箇所が多くてもお互いに負担にならないよう，次からは PR にコメントするのではなくて直接ブランチにコミットする形でレビューを行うのが良さそうですね．

ありがとうございました．ほかの節も PR いただけたらレビューいたします．

2023-11-16 05:31 UTC, ihuku commented
@Seasawher お礼が遅くなり申し訳ありません。ご対応いただきまして、ありがとうございました！

2023-12-26 03:01 UTC, Seasawher commented
@ihuku 

ご無沙汰しております．もし今でも functional programming in lean の翻訳に興味を持っていただけているようでしたら，こちらのDiscordサーバにぜひおいでください．

https://discord.gg/p32ZfnVawh

PRのコメント上だと大変だったので，音声通話をしながら Live Share を使う方法をとりたいと思っています．